version: "3.6"
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.8.4
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "key": "-----BEGIN PUBLIC KEY-----\nMFswDQYJKoZIhvcNAQEBBQADSgAwRwJAdL1NXWAO2AF9FT6Zm3OS9k81q35tuXLS\nITBBUsn0HT1RstUTNMzjTj8ZKA0bdrtx7Jlv6uy0lmLjpp9lF/q0UQIDAQAB\n-----END PUBLIC KEY-----"}'
      SERVER_URL: http://localhost:9090
      API_KEY: "someapikeyfordevlopment"
volumes:
  db_data:
