version: "3.6"
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PGADMIN_DEFAULT_EMAIL: anand252825@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123nithesh@
    ports:
      - "5050:80"
  graphql-engine:
    image: hasura/graphql-engine:v2.8.4
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "key": "-----BEGIN PUBLIC KEY-----\nMFswDQYJKoZIhvcNAQEBBQADSgAwRwJAZoYjrlOFcxVIZAl9EPz2LH/abHe7NJnh\nUUa6l9aawQDr3q9zAdOsD7gRB/ec00R3EVUnrETyE/ckdYXIAohgHwIDAQAB\n-----END PUBLIC KEY-----"}'
      SERVER_URL: http://host.docker.internal:9090
      API_KEY: "someapikeyfordevlopment"
volumes:
  db_data:
