-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."bill" add column "payment_initiated" boolean
--  null default 'false';
