name: Build and Deploy React App to CloudFront

"on":
  push:
    branches:
      - production
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      VITE_BASE_FIREBASE: ${{secrets.BASE_FIREBASE}}
      VITE_BASE_URL: https://hasura.infraweigh.co
      VITE_BASE_WS_URL: wss://hasura.infraweigh.co
      VITE_RAZORPAY_ID: ${{secrets.RAZORPAY_ID}}
      VITE_SERVER_URL: https://server.infraweigh.co
      VITE_ENV: production
      BUCKET: terminal.infraweigh.co
      DIST: packages/terminal/dist
      REGION: ap-south-1
      DIST_ID: E11FX7T6Q6VRGG
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_FOR_HOSTING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_FOR_HOSTING }}
          aws-region: us-east-1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn install
          working-directory: packages/terminal

      - name: Build Static Website
        run: yarn build

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
