name: aws static hosting deployment
"on":
  push:
    branches:
      - production
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      VITE_BASE_FIREBASE: ${{secrets.BASE_FIREBASE}}
      VITE_BASE_URL: ${{secrets.BASE_URL}}
      VITE_BASE_WS_URL: ${{secrets.BASE_WS_URL}}
      VITE_RAZORPAY_ID: ${{secrets.RAZORPAY_ID}}
      VITE_ENV: production
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_FOR_HOSTING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_FOR_HOSTING }}
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn install
          working-directory: packages/terminal
      - name: Build
        run: yarn build
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: packages/terminal/dist
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          private: true
          filesToInclude: ".*/*,*/*,**"
