name: hasura staging deployment

"on":
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn install
          working-directory: packages/terminal
      - name: build apps
        run: cd packages/hasura && yarn hasura deploy --admin-secret ${{secrets.ADMIN_SECRET}} --endpoint ${{secrets.BASE_URL_STAGING}}
