name: Firebase function deploy

"on":
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NX_BASE_FIREBASE: ${{secrets.NX_BASE_FIREBASE}}
      NX_BASE_URL: ${{secrets.NX_BASE_URL}}
      NX_RAZORPAY_ID: ${{secrets.NX_RAZORPAY_ID}}
      NX_BASE_WS_URL: ${{secrets.NX_BASE_WS_URL}}
      NX_ENV: production
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}

          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install npm packages and build the app
        run: npm i -g yarn firebase firebase-tools && cd scripts && yarn build && cd .. && cd firebase/functions && yarn install && yarn build && cd .. && firebase use default && firebase deploy --token $FIREBASE_TOKEN
