name: build container for server

on:
  push:
    branch: production
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: ${{ secrets.REPO_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_UPLOAD_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_UPLOAD_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn install
          working-directory: packages/server

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container and push it to ECR
          cd packages/server
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
