name: Deploy staging server to heroku.

"on":
  push:
    branches:
      - staging/packages/server/**jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a staging Docker container to Heroku.
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email : anand@infraweigh.co
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: infraweigh-server
          appdir: packages/server
          usedocker: true
  