name: Firebase function deploy

"on":
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_ENV: staging
      ENV: staging
      NODE_ENV: staging
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn install
          working-directory: |
            packages/terminal
            packages/serverless

      - name: build apps
        run: yarn build && cd packages/serverless && yarn deploy:staging --token $FIREBASE_TOKEN
